.TH BLINDTTY 1 2006-11-14

.SH NAME
blindtty - Run command in a blind terminal

.SH SYNOPSIS
.B blindtty CMD [ARGS]...

.SH DESCRIPTION

.B blindtty
runs a command in a blind terminal. This is very similar to redirecting
all its I/O to /dev/null, but the application retains a perception of
being ran on a terminal, even though it will not ever receive any input
and noone will see its output. This is useful if you want to run an
application "detached" now but want to attach it later using
\fBretty(1)\fR.

You might find it useful to run it as:
.br
.B setsid blindtty CMD...
.br
In that case it will really detach from your terminal and start a separate
session.

.RE
.SH AUTHORS
Written and maintained by Petr Baudis <pasky@ucw.cz> and Jan Sembera
<jan.sembera@innoxia.cz>.

.RE
.SH "SEE ALSO"
retty(1), setsid(8), screen(1)
