.TH BLINDTTY 1 2006-11-14

.SH NAME
blindtty - Run command in a detached terminal

.SH SYNOPSIS
.B blindtty CMD [ARGS]...

.SH DESCRIPTION

.B blindtty
runs a command in a detached terminal.
You might find it useful to run it as "setsid blindtty CMD...".

.RE
.SH "SEE ALSO"
retty(1), setsid(8), screen(1)
