attach-ia32-linux.o: arch/attach-ia32-linux.o
	mv arch/attach-ia32-linux.o attach-ia32-linux.o

detach-ia32-linux.o: arch/detach-ia32-linux.o
	mv arch/detach-ia32-linux.o detach-ia32-linux.o

attach-x86_64-linux.o: arch/attach-x86_64-linux.o
	mv arch/attach-x86_64-linux.o attach-x86_64-linux.o

detach-x86_64-linux.o: arch/detach-x86_64-linux.o
	mv arch/detach-x86_64-linux.o detach-x86_64-linux.o

attach-arm-linux.o: arch/attach-arm-linux.o
	mv arch/attach-arm-linux.o attach-arm-linux.o

detach-arm-linux.o: arch/detach-arm-linux.o
	mv arch/detach-arm-linux.o detach-arm-linux.o

attach-none-none.o: arch/attach-none-none.o

detach-none-none.o: arch/detach-none-none.o
