attach-ia32-linux.o: arch/attach-ia32-linux.o
	mv arch/attach-ia32-linux.o attach-ia32-linux.o

detach-ia32-linux.o: arch/detach-ia32-linux.o
	mv arch/detach-ia32-linux.o detach-ia32-linux.o

attach-none-none.o: arch/attach-none-none.o

detach-none-none.o: arch/detach-none-none.o
